spring:
  application:
    name: knowledge-archive
  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      exposure:
        include: prometheus